function showError(message) {
  try {
    alert("message")
  }
  catch {
    Logger.log("message")
  }
  return null
}
